## **1. Abstract**

**"How are social media use patterns associated with mental health, sleep quality, and productivity among young adults?"**

## **1.1 Group Members**

1. Jose Paulo Honrado
2. King Mejia
3. Mikael Paule
4. Heart rodrigo
5. Kenji Yasuda

## **2. Dataset Description**

### **2.1 Dataset Selection**

The study will primarily use the *smmh.csv* from the Kaggle dataset *Social Media and Mental Health* because it contains variables that is directly related to social media use, mental health, sleep quality, and productivity-related bahviors. There are also two additional datasets, *Mental_Health_and_Social_Media_Balance_Dataset.csv* and *Social Media Impact on Daily Lives.csv*, will be treated as supporting datasets. These datasets may be used for comparison, but will not be merged into one dataset because each dataset varies from sources, respondents, and variables.

### **2.2 Primary Dataset: smmh.csv**

| Item | Description |
|---|---|
| Source | Kaggle: *Social Media and Mental Health* |
| File used | `smmh.csv` |
| Observations | 481 survey respondents |
| Variables | 21 columns |
| Unit of observation | Each row represents one respondent's response |
| General topic | Social media habits and *self-reported* mental health, sleep, and attention-related experiences |

The dataset contains survey responses about the respondents' demographic, amount of time spent on social media, platform preferences, and self-reported behaviors. Specifically including, using social media without a purpose, distraction, restlessness, worriness, concentration, comparison with others, validation-seeking, feeling depressed, fluctuation on everyday activities, and sleep issues.

The dataset was collected through a survey for a university statistics course project, which focused on different aspects of mental health and how a participant feels any effect on social media use. However, the Kaggle description of the dataset did not specify whether the respondents were randomly selected, how the survey was given, or if the survey was done online or offline. This makes the sampling method unclear and may not fully represent a broad population of young adults. Therefore, the findings from this dataset should be interpreted within the surveyed respondents from the dataset and not towards the population of all young adults.

Since the sampling method was not specified, there is a possibility of having a sampling bias. The dataset may be affected by voluntary response bias or convenience bias. However, it is hard to conclude if there was a bias in this dataset and should be treated as possible limitations because the source of the dataset does not provide enough information about the sampling processes of this dataset.

### **2.3 Attributes of the Primary Dataset**

| Attribute | Columns/Variables | Description |
|---|---|---|
| Response Metadata | Timestamp | Date and time when the survery response was submitted. |
| Demographics | Age, gender, relationship status, occupation status, organization affiliation | Describes the respondent's background and identifies the target group of young adults |
| Social Media access and platforms | Social media use, commonly used platforms | Identifies whether the respondent uses social media and which platforms they use. |
| Social media usage intensity | Average daily time spent on social media | Describes the main variable for comparing heavier-usage and lighter-usage users. |
| Social media behavior patterns | Purposeless use, distracted while bust, restlessness after not using social media | Measures the possible compulsive or disruptive social media behaviors. |
| Productivity-related indicators | Ease of distraction, difficulty concentrating | Used as indicators of productivity or focus difficulties. |
| Mental health indicators | Worry, comparison with others, feelings about comparison, validation-seeking, feeling depressed, fluctuation of interest in daily activities | Used to explore mental health-related patterns associated with social media use. |
| Sleep indicator | Frequency of sleep issues | Used to check the relationship between social media use and sleep-related problems. |

### **2.4 Supporting Datasets**

| Dataset | Source | Observations | Variables | Possible Use-Case |
|---|---|---|---|---|
| Mental_Health_and_Social_Media_Balance_Dataset.csv | Kaggle: Mental Health & Social Media Balance Dataset | 500 | 10 | A supporting dataset that can be used to compare screen time, sleep quality, stress, happiness, exercise, and days without social media. |
| Social Media Impact on Daily Lives.csv | Mendeley Data: The Impact of Social Media on Daily Lives | 522 | 16 | A supporting dataset that can be used to compare daily social media use, addiction, time management, profession, and family time. |

### **2.5 Limitations**

The datasets could be useful for exploring correlations between social media and the well-being of someone, but this comes with limitations. Firstly, the datasets come from different sources, their rows do not represent the same respondents and their columns are not exactly the same either making it difficult to merge the datasets. Second, a lot of these variables are subjective, which may have some bias towards the data. Finally, there is a huge difference in population, survey design, and measurement scales, which could affect how well the comparison of datasets will be.

## **3.0 Data Cleaning & Preprocessing**

### **3.1 Imports and Setup**

In [3]:
import pandas as pd
import numpy as np

#Load datasets
df1 = pd.read_csv('../data/raw/smmh.csv')
df2_raw = pd.read_csv('../data/raw/Mental_Health_and_Social_Media_Balance_Dataset.csv')
df3_raw = pd.read_csv('../data/raw/Social_Media_Impact_on_Daily_Lives.csv')

ModuleNotFoundError: No module named 'pandas'

### **3.2 Preprocessing Datasets**

#### **3.2.1 Renaming Columns to Clean Variables (DF1)**

Right now the long survey text strings makes the data messy. So, we map these long titles into clear and concise feature names.

In [18]:
df1 = df1.rename(columns={
    'Timestamp': 'timestamp',
    '1. What is your age?': 'age',
    '2. Gender': 'gender',
    '3. Relationship Status': 'relationship_status',
    '4. Occupation Status': 'occupation_status',
    '5. What type of organizations are you affiliated with?': 'organization_affiliations',
    '6. Do you use social media?': 'uses_social_media',
    '7. What social media platforms do you commonly use?': 'platforms_used',
    '8. What is the average time you spend on social media every day?': 'daily_time_spent',
    '9. How often do you find yourself using Social media without a specific purpose?': 'purposeless_usage',
    '10. How often do you get distracted by Social media when you are busy doing something?': 'distraction_frequency',
    '11. Do you feel restless if you haven\'t used Social media in a while?': 'restlessness_score',
    '12. On a scale of 1 to 5, how easily distracted are you?': 'distraction_scale',
    '13. On a scale of 1 to 5, how much are you bothered by worries?': 'worry_scale',
    '14. Do you find it difficult to concentrate on things?': 'concentration_difficulty',
    '15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?': 'social_comparison_frequency',
    '16. Following the previous question, how do you feel about these comparisons, generally speaking?': 'comparison_sentiment',
    '17. How often do you look to seek validation from features of social media?': 'validation_seeking',
    '18. How often do you feel depressed or down?': 'depression_scale',
    '19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?': 'interest_fluctuation',
    '20. On a scale of 1 to 5, how often do you face issues regarding sleep?': 'sleep_issue_scale'
})

In [22]:
df1.head(0)

Empty DataFrame
Columns: [Timestamp, 1. What is your age?, 2. Gender, 3. Relationship Status, 4. Occupation Status, 5. What type of organizations are you affiliated with?, 6. Do you use social media?, 7. What social media platforms do you commonly use?, 8. What is the average time you spend on social media every day?, 9. How often do you find yourself using Social media without a specific purpose?, 10. How often do you get distracted by Social media when you are busy doing something?, 11. Do you feel restless if you haven't used Social media in a while?, 12. On a scale of 1 to 5, how easily distracted are you?, 13. On a scale of 1 to 5, how much are you bothered by worries?, 14. Do you find it difficult to concentrate on things?, 15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?, 16. Following the previous question, how do you feel about these comparisons, generally speaking?, 17. How often do you look to seek validation from features of social media?, 18. How often do you feel depressed or down?, 19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?, 20. On a scale of 1 to 5, how often do you face issues regarding sleep?]
Index: []

[0 rows x 21 columns]

#### **3.2.2 Renaming Columns to Clean Variables (DF2)**

In [ ]:
# Create a separate dataframe
df2_clean = df2_raw.copy()

In [ ]:
df2_clean = df2_clean.rename(columns={
    'User_ID': 'user_id',
    'Age': 'age',
    'Gender': 'gender',
    'Daily_Screen_Time(hrs)': 'daily_screen_time_hours',
    'Sleep_Quality(1-10)': 'sleep_quality',
    'Stress_Level(1-10)': 'stress_level',
    'Days_Without_Social_Media': 'days_without_social_media',
    'Exercise_Frequency(week)': 'exercise_frequency_week',
    'Social_Media_Platform': 'primary_social_media_platform',
    'Happiness_Index(1-10)': 'happiness_index'
})

In [ ]:
df2_clean['source_dataset'] = 'Mental_Health_and_Social_Media_Balance_Dataset.csv'

#### **3.2.3 Renaming and Dropping Columns (DF3)**

In [4]:
# Create a separate dataframe for the cleaned dataset.
df3_clean = df3_raw.copy()

In [5]:
# Drop columns that we think are not useful. (Note: "Unnamed: 0" seems to be a duplicate of the first column in the original csv file).
# We wouldn't need to know the name of the respondents. 
# We wouldn't need to know what the respondents think about 'privacy policies'. 
# We wouldn't need to know a respondent's influence when purchasing a product.

df3_clean = df3_clean.drop(columns=["Unnamed: 0", 
                                    "Enter your name",
                                    "Do you think privacy policies are effective in social networking sites?",
                                    "Does social media advertising influence the purchase of your product?"])

df3_clean.columns

Index(['Enter your age (Ex: 20)', 'What is your gender',
       'What is your profession?',
       'On an average how many hours a day you spend on your profession?',
       'What social networking sites do you use?',
       'On an average how many hours a day do you spend on these sites?',
       'On an average how many hours a day do you spend with your family?',
       'Why do you use these social networking sites?',
       'What are personal benefits of  using social networking sites?',
       'When do you access social media websites?',
       'When you use social media did you forget about time?',
       'Do you consider yourself addicted to social media?'],
      dtype='str')

**IMPORTANT: In the original csv file, there is a double space in one of the columns "What are personal benefits of  using social networking sites?"**

In [6]:
# After double checking the column names, rename each column to make it simplier for readability.
df3_clean = df3_clean.rename(columns={
    'Enter your age (Ex: 20)': 'age',
    'What is your gender': 'gender',
    'What is your profession?': 'occupation',
    'On an average how many hours a day you spend on your profession?': 'daily_occupation_hours',
    'What social networking sites do you use?': 'social_media_platforms',
    'On an average how many hours a day do you spend on these sites?': 'daily_social_media_hours',
    'On an average how many hours a day do you spend with your family?': 'daily_family_hours',
    'Why do you use these social networking sites?': 'social_media_use_reasons',
    'What are personal benefits of  using social networking sites?': 'perceived_social_media_benefits',
    'When do you access social media websites?': 'times_using_social_media',
    'When you use social media did you forget about time?': 'forget_time_using_social_media',
    'Do you consider yourself addicted to social media?': 'subjective_social_media_addiction'
})

In [7]:
# In case we would use this dataset for numerical analysis later (averages, correlations, scatterplots, or any statistical test). 
# So, instead of a range, we would have solid values. This does not change the original column, but rather it creates a new column.
hour_mapping = {
    "0-2": 1,
    "1-2": 1.5,
    "2-4": 3,
    "3-4": 3.5,
    "4-5": 4.5,
    "4-6": 5,
    "5-6": 5.5,
    "6-8": 7,
    "6+": 6,
    "8+": 8
}

df3_clean["daily_occupation_hours_num"] = df3_clean["daily_occupation_hours"].map(hour_mapping)
df3_clean["daily_social_media_hours_num"] = df3_clean["daily_social_media_hours"].map(hour_mapping)
df3_clean["daily_family_hours_num"] = df3_clean["daily_family_hours"].map(hour_mapping)

In [ ]:
# Filter ages to our desired range (18-30)
df3_clean.query("age > 18 & age < 30")

,age,gender,occupation,daily_occupation_hours,social_media_platforms,daily_social_media_hours,daily_family_hours,social_media_use_reasons,perceived_social_media_benefits,times_using_social_media,forget_time_using_social_media,subjective_social_media_addiction,daily_occupation_hours_num,daily_social_media_hours_num,daily_family_hours_num
0,22,male,student,6-8,"facebook, youtube, instagram, imo, telegram, w...",6+,1-2,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during meal times",yes,yes,7.0,6.0,1.5
1,23,male,student,6-8,"facebook, youtube, imo, telegram, whatsapp, li...",4-5,1-2,"keep up with news/gossip/ trends, contact and ...","staying connected with people, learn new skills","during my free time, during meal times, any sp...",sometimes,no,7.0,4.5,1.5
2,24,male,student,2-4,"facebook, youtube, instagram, telegram, whatsapp",4-5,1-2,"keep up with news/gossip/ trends, contact and ...",staying connected with people,during my free time,yes,yes,3.0,4.5,1.5
3,23,male,student,8+,"facebook, youtube",4-5,4-5,"keep up with news/gossip/ trends, contact and ...","help with studies, entertainment","during my free time, any spare time",no,yes,8.0,4.5,4.5
4,20,male,student,6-8,"facebook, youtube, telegram, whatsapp",1-2,6+,"keep up with news/gossip/ trends, contact and ...","keep up with news/gossip/ trends, contact and ...","during my free time, during meal times",no,no,7.0,1.5,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,20,female,student,0-2,facebook,3-4,1-2,contact and connect with friends/ family,staying connected with people,while at school/university/work,no,no,1.0,3.5,1.5
518,21,female,student,6-8,"facebook, youtube, instagram, whatsapp",1-2,1-2,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, while at school/universit...",sometimes,no,7.0,1.5,1.5
519,22,male,student,2-4,"facebook, youtube, telegram, whatsapp",3-4,6+,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during meal times, any sp...",sometimes,not sure,3.0,3.5,6.0
520,21,female,student,4-6,"facebook, youtube, instagram, telegram, whatsapp",1-2,1-2,"keep up with news/gossip/ trends, contact and ...",help with studies,during my free time,sometimes,no,5.0,1.5,1.5
521,22,male,student,2-4,"facebook, youtube, instagram, telegram, whatsapp",3-4,3-4,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during social occasions",no,no,3.0,3.5,3.5

## **Research Question & Exploratory Data Analysis**

## **Summary, Conclusions, and Recommendations**

## **References & Disclosures**